spring:
  application:
    name: tanzu-java-web-app
  datasource:
    driver-class-name: org.postgresql.Driver
    password: {password}
    url: {uri}
    username: {username}
org:
  springframework:
    cloud:
      bindings:
        boot:
          postgresql:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
